---
# Build the ESPHome binary firmware
# And deploy it to Github Pages.
name: Publish firmware

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  publish:
    name: "üõ†Ô∏è ESPHome S0tool compleet"
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: esphome/pulscounter.yaml
      name: S0tool compleet