---
# Build the ESPHome binary firmware
# And deploy it to Github Pages.
name: Publish firmware pull request

on:
  pull_request:


jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - esphome/pulscounter.yaml #standard version
          - esphome/watermeter.yaml  # only watermeter
          - esphome/S0-puls-kwhpuls.yaml  # only kwh puls 
          - esphome/S0-puls-DSZ12D.yaml   # Special
          - esphome/S0-puls-LEM022SJ.yaml  #special
          - esphome/s0-watermeter.yaml # special watermeter
    #      - esphome/pulscounter_flux.yaml # special standaard for flow sensors & pulscounter
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v1.7.0
        with:
          yaml_file: ${{ matrix.file }}
