---
# Build the ESPHome binary firmware
# And deploy it to Github Pages.
name: Publish firmware

on:
  push:
    branches:
      - main

jobs:
  publish-S0tool-compleet:
    name: "üõ†Ô∏è ESPHome S0tool firmware"
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: ./esphome/pulscounter.yaml
      name: S0tool
      manifest_filename: s0tool-manifest.json
