---
# Build the ESPHome binary firmware
# And deploy it to Github Pages.
name: Publish firmware

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: "ğŸ› ï¸ ESPHome firmware"
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: ./esphome/pulscounter.yaml
      name: S0tool
