name-template: v$NEXT_PATCH_VERSION
categories:
  - title: ğŸš€ Features
    label: feature
  - title: ğŸ› Bug Fixes
    label: fix
  - title: ğŸ§° Maintenance
    label: chore
template: |
  ## Changes

  $CHANGES